language: node_js
node_js:
  - '0.10'
before_install:
  - 'npm install -g npm@2.5.1'
  - 'npm install -g bower'
before_script:
  - 'npm install -g grunt-cli'
notifications:
  slack:
    rooms:
      - softwaresandbox:wSLhmu5v2ZHNq0PpgTrFBbSe#fiangulartje
      - fiangulartje:AccRWcnglPImsSDKzKYauQQj#general
